### ISSUE TITLE
Browser access poweradmin error

### ISSUE THREAD

**Issue by paddy235** [julianxhokaxhiu/docker-powerdns#7]
```
pdns_1  | Sep 25 05:15:37 [1] dropping UDP query from 10.150.60.129, address not matched by allow-from
pdns_1  | Sep 25 05:15:37 [1] dropping UDP query from 10.150.60.129, address not matched by allow-from
pdns_1  | Sep 25 05:15:38 [1] dropping UDP query from 10.150.60.90, address not matched by allow-from
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:38] "GET / HTTP/1.1" 500 -
pdns_1  | Traceback (most recent call last):
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
pdns_1  |     return self.wsgi_app(environ, start_response)
pdns_1  |   File "/usr/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
pdns_1  |     return self.app(environ, start_response)
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
pdns_1  |     response = self.handle_exception(e)
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
pdns_1  |     reraise(exc_type, exc_value, tb)
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
pdns_1  |     raise value
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
pdns_1  |     response = self.full_dispatch_request()
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
pdns_1  |     self.try_trigger_before_first_request_functions()
pdns_1  |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
pdns_1  |     func()
pdns_1  |   File "/usr/share/webapps/powerdns-admin/app/views.py", line 55, in register_modules
pdns_1  |     google = google_oauth()
pdns_1  |   File "/usr/share/webapps/powerdns-admin/app/oauth.py", line 47, in google_oauth
pdns_1  |     if not Setting().get('google_oauth_enabled'):
pdns_1  |   File "/usr/share/webapps/powerdns-admin/app/models.py", line 1920, in get
pdns_1  |     result = self.query.filter(Setting.name == setting).first()
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2789, in first
pdns_1  |     ret = list(self[0:1])
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2581, in __getitem__
pdns_1  |     return list(res)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
pdns_1  |     return self._execute_and_instances(context)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
pdns_1  |     result = conn.execute(querycontext.statement, self._params)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
pdns_1  |     return meth(self, multiparams, params)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
pdns_1  |     return connection._execute_clauseelement(self, multiparams, params)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
pdns_1  |     compiled_sql, distilled_params
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
pdns_1  |     context)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
pdns_1  |     exc_info
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
pdns_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
pdns_1  |     raise value.with_traceback(tb)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
pdns_1  |     context)
pdns_1  |   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
pdns_1  |     cursor.execute(statement, parameters)
pdns_1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: setting [SQL: 'SELECT setting.id AS setting_id, setting.name AS setting_name, setting.value AS setting_value \nFROM setting \nWHERE setting.name = ?\n LIMIT ? OFFSET ?'] [parameters: ('google_oauth_enabled', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:41] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:41] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:41] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:42] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:43] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
pdns_1  | [INFO] 10.150.30.99 - - [25/Sep/2018 05:15:43] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
pdns_1  | Sep 25 05:15:51 [1] dropping UDP query from 10.150.20.7, address not matched by allow-from
pdns_1  | Sep 25 05:15:52 [1] dropping UDP query from 10.150.101.17, address not matched by allow-from
pdns_1  | Sep 25 05:15:55 [1] dropping UDP query from 10.150.60.164, address not matched by allow-from
pdns_1  | Sep 25 05:15:57 [1] dropping UDP query from 10.150.101.253, address not matched by allow-from
pdns_1  | Sep 25 05:15:57 [1] dropping UDP query from 10.150.10.9, address not matched by allow-from
pdns_1  | Sep 25 05:15:57 [1] dropping UDP query from 10.150.101.17, address not matched by allow-from
```

**Comment by julianxhokaxhiu** [comment]
A new build will be published soon.

**Comment by julianxhokaxhiu** [comment]
Container has now been published: https://hub.docker.com/r/julianxhokaxhiu/docker-powerdns/builds/bapwzhfhuahjyqwtnrvuz6a/
